spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/order_db
    username: reza
    password: reza
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.reza.ecommerce.kafka.OrderConfirmation

server:
  port: 8092

application:
  config:
    #direct hit to service without eureka/API GW
    #    customer-url: http://localhost:8090/api/v1/customers
    #    payment-url: http://localhost:8093/api/v1/payments
    #    product-url: http://localhost:8091/api/v1/products

    #hit to service by eureka/API GW
    customer-url: http://localhost:8222/api/v1/customers
    payment-url: http://localhost:8222/api/v1/payments
    product-url: http://localhost:8222/api/v1/products