spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/product_db
    username: reza
    password: reza
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    repair: true
    enabled: true
    baseline-description: "db init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
server:
  port: 8091

